create table if not exists public.property_types (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null unique
);

create table if not exists public.cities (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.areas (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.cities (id) on delete cascade,
  name text not null,
  unique (city_id, name)
);

create table if not exists public.utilities (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null unique
);

create table if not exists public.listing_contacts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users (id) on delete cascade,
  first_name text not null,
  last_name text not null default '',
  whatsapp_number text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.listing_images (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings (id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.listing_utilities (
  listing_id uuid not null references public.listings (id) on delete cascade,
  utility_id bigint not null references public.utilities (id) on delete cascade,
  primary key (listing_id, utility_id)
);

insert into public.property_types (code, label)
values
  ('room', 'Room'),
  ('bachelor', 'Bachelor'),
  ('shared', 'Shared'),
  ('flat', 'Flat'),
  ('house', 'House')
on conflict (code) do update
set label = excluded.label;

insert into public.utilities (code, label)
values
  ('water', 'Water'),
  ('electricity', 'Electricity'),
  ('wifi', 'WiFi')
on conflict (code) do update
set label = excluded.label;

alter table public.listings
add column if not exists property_type_id bigint references public.property_types (id),
add column if not exists city_id bigint references public.cities (id),
add column if not exists area_id bigint references public.areas (id),
add column if not exists contact_id uuid references public.listing_contacts (id);

insert into public.cities (name)
select distinct city
from public.listings
where city is not null
on conflict (name) do nothing;

insert into public.areas (city_id, name)
select distinct cities.id, listings.suburb
from public.listings
join public.cities cities on cities.name = listings.city
where listings.suburb is not null
on conflict (city_id, name) do nothing;

update public.listings listings
set property_type_id = property_types.id
from public.property_types property_types
where lower(property_types.label) = lower(listings.property_type)
  and listings.property_type_id is null;

update public.listings listings
set city_id = cities.id
from public.cities cities
where cities.name = listings.city
  and listings.city_id is null;

update public.listings listings
set area_id = areas.id
from public.areas areas
join public.cities cities on cities.id = areas.city_id
where cities.name = listings.city
  and areas.name = listings.suburb
  and listings.area_id is null;

insert into public.listing_contacts (user_id, first_name, last_name, whatsapp_number)
select distinct on (listings.user_id)
  listings.user_id,
  split_part(trim(listings.poster_name), ' ', 1),
  case
    when strpos(trim(listings.poster_name), ' ') > 0 then trim(substr(trim(listings.poster_name), strpos(trim(listings.poster_name), ' ') + 1))
    else ''
  end,
  listings.whatsapp_number
from public.listings listings
where listings.user_id is not null
  and listings.poster_name is not null
  and listings.whatsapp_number is not null
on conflict (user_id) do update
set
  first_name = excluded.first_name,
  last_name = excluded.last_name,
  whatsapp_number = excluded.whatsapp_number,
  updated_at = timezone('utc', now());

insert into public.listing_contacts (first_name, last_name, whatsapp_number)
select
  split_part(trim(listings.poster_name), ' ', 1),
  case
    when strpos(trim(listings.poster_name), ' ') > 0 then trim(substr(trim(listings.poster_name), strpos(trim(listings.poster_name), ' ') + 1))
    else ''
  end,
  listings.whatsapp_number
from public.listings listings
where listings.user_id is null
  and listings.poster_name is not null
  and listings.whatsapp_number is not null;

update public.listings listings
set contact_id = contacts.id
from public.listing_contacts contacts
where listings.user_id is not null
  and contacts.user_id = listings.user_id
  and listings.contact_id is null;

update public.listings listings
set contact_id = contacts.id
from public.listing_contacts contacts
where listings.user_id is null
  and contacts.user_id is null
  and contacts.whatsapp_number = listings.whatsapp_number
  and contacts.first_name = split_part(trim(listings.poster_name), ' ', 1)
  and contacts.last_name = case
    when strpos(trim(listings.poster_name), ' ') > 0 then trim(substr(trim(listings.poster_name), strpos(trim(listings.poster_name), ' ') + 1))
    else ''
  end
  and listings.contact_id is null;

insert into public.listing_images (listing_id, image_url, sort_order)
select listings.id, listings.image_url, 0
from public.listings listings
where listings.image_url is not null
  and not exists (
    select 1
    from public.listing_images images
    where images.listing_id = listings.id
  );

insert into public.listing_utilities (listing_id, utility_id)
select listings.id, utilities.id
from public.listings listings
cross join lateral unnest(coalesce(listings.utilities_included, '{}')) as utility_label(label)
join public.utilities utilities on lower(utilities.label) = lower(utility_label.label)
on conflict do nothing;

alter table public.property_types enable row level security;
alter table public.cities enable row level security;
alter table public.areas enable row level security;
alter table public.utilities enable row level security;
alter table public.listing_contacts enable row level security;
alter table public.listing_images enable row level security;
alter table public.listing_utilities enable row level security;

create policy "Property types are viewable by everyone"
  on public.property_types
  for select
  using (true);

create policy "Cities are viewable by everyone"
  on public.cities
  for select
  using (true);

create policy "Authenticated users can create cities"
  on public.cities
  for insert
  to authenticated
  with check (true);

create policy "Areas are viewable by everyone"
  on public.areas
  for select
  using (true);

create policy "Authenticated users can create areas"
  on public.areas
  for insert
  to authenticated
  with check (true);

create policy "Utilities are viewable by everyone"
  on public.utilities
  for select
  using (true);

create policy "Listing contacts are viewable by everyone"
  on public.listing_contacts
  for select
  using (true);

create policy "Authenticated users can create listing contacts"
  on public.listing_contacts
  for insert
  to authenticated
  with check (user_id is null or user_id = auth.uid());

create policy "Authenticated users can update their listing contact"
  on public.listing_contacts
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "Listing images are viewable by everyone"
  on public.listing_images
  for select
  using (true);

create policy "Authenticated users can create images for their listings"
  on public.listing_images
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.listings listings
      where listings.id = listing_id
        and listings.user_id = auth.uid()
    )
  );

create policy "Authenticated users can update images for their listings"
  on public.listing_images
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.listings listings
      where listings.id = listing_id
        and listings.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.listings listings
      where listings.id = listing_id
        and listings.user_id = auth.uid()
    )
  );

create policy "Authenticated users can delete images for their listings"
  on public.listing_images
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.listings listings
      where listings.id = listing_id
        and listings.user_id = auth.uid()
    )
  );

create policy "Listing utilities are viewable by everyone"
  on public.listing_utilities
  for select
  using (true);

create policy "Authenticated users can create utilities for their listings"
  on public.listing_utilities
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.listings listings
      where listings.id = listing_id
        and listings.user_id = auth.uid()
    )
  );

create policy "Authenticated users can delete utilities for their listings"
  on public.listing_utilities
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.listings listings
      where listings.id = listing_id
        and listings.user_id = auth.uid()
    )
  );
